version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo Installing dependencies...
      - pip install --no-cache-dir flask

  build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/s9n9d4c6
      - echo Building the Docker image...
      - docker build -t parmar-repo .
      - echo Tagging the Docker image...
      - docker tag parmar-repo:latest public.ecr.aws/s9n9d4c6/parmar-repo:latest
      - echo Pushing the Docker image to Amazon ECR...
      - docker push public.ecr.aws/s9n9d4c6/parmar-repo:latest
      - echo Creating imageDefinitions.json for ECS deployment...
      - echo '[{"name":"parmar-flask-app","imageUri":"public.ecr.aws/s9n9d4c6/parmar-repo:latest"}]' > imageDefinitions.json

artifacts:
  files:
    - app.py
    - requirements.txt
    - imageDefinitions.json
