version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
      docker: 20
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade pip
      - pip install awscli

  pre_build:
    commands:
      - echo "Logging in to Amazon ECR Public..."
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/s9n9d4c6
      - echo "Pre-build phase completed."

  build:
    commands:
      - echo "Building the Docker image..."
      - docker build -t parmar-repo .
      - echo "Tagging the Docker image..."
      - docker tag parmar-repo:latest public.ecr.aws/s9n9d4c6/parmar-repo:latest

  post_build:
    commands:
      - echo "Pushing the Docker image to Amazon ECR Public..."
      - docker push public.ecr.aws/s9n9d4c6/parmar-repo:latest
      - echo "Build and push process completed."

artifacts:
  files:
    - "**/*"
  discard-paths: yes
  base-directory: /

cache:
  paths:
    - "/root/.cache/pip/**/*"
